all:
	@echo "--- START BUILD DYNAMIC ALLOCATION ---"
	gcc main.c -o main
	@echo "--- DONE BUILD DYNAMIC ALLOCATION ---"
clean:
	@echo "--- START BUILD DYNAMIC ALLOCATION ---"
	rm main
	@echo "--- DONE BUILD DYNAMIC ALLOCATION ---"
